# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/83cdc51e-a8aa-4e7e-85c3-b55d6b7a0dc5";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-6564bf58-df87-489a-9791-e9de689c78c2".device = "/dev/disk/by-uuid/6564bf58-df87-489a-9791-e9de689c78c2";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/642C-F90F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/587cf480-b794-4920-a456-37d85bfebaa5"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
